name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'Test'

      age:
        description: 'Age'
        type: Number
        required: true

      gender:
        description: 'Gender'
        type: Choice
        options:
          - Male
          - Female
    
jobs:
  Demo:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: echo "${{ inputs.name }}"

      - name: Age
        run: echo ${{ inputs.age }}

      - name: Gender
        run: echo ${{ inputs.gender }}
